# Generated by Django 5.0.7 on 2026-06-27 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary login identifier for the user.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="User job title, such as Support Engineer or Platform Admin.",
                        max_length=255,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department the user belongs to.",
                        max_length=255,
                    ),
                ),
                (
                    "is_support_engineer",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to work support tickets.",
                    ),
                ),
                (
                    "is_security_reviewer",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to review security-sensitive escalations.",
                    ),
                ),
                (
                    "is_platform_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to manage platform-level configuration.",
                    ),
                ),
                (
                    "can_approve_ai_responses",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to approve AI-generated customer responses.",
                    ),
                ),
                (
                    "can_approve_code_fixes",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to approve AI-generated code changes.",
                    ),
                ),
                (
                    "can_override_policies",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to override governance policies.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the user was active in the platform.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["email"],
                "indexes": [
                    models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
                    models.Index(
                        fields=["is_platform_admin"],
                        name="accounts_us_is_plat_ec674e_idx",
                    ),
                    models.Index(
                        fields=["is_support_engineer"],
                        name="accounts_us_is_supp_7e618e_idx",
                    ),
                ],
            },
        ),
    ]
